// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package users

import (
	"database/sql"
)

type User struct {
	ID         string
	Username   string
	WebhookUrl sql.NullString
	Created    sql.NullTime
}

type UserAlert struct {
	AlertID int32
	ID      string
	Keyword string
	Ignored []string
}
